import type { ToolMeta } from '../types';

export const CATEGORY_LABELS: Record<ToolMeta['category'], string> = {
  essentials: 'Essentials',
  productivity: 'Productivity',
  finance: 'Finance',
  more: 'More',
};

export const TOOLS: ToolMeta[] = [
  {
    id: 'calculator',
    name: 'Calculator',
    shortDescription: 'Basic calculator with history',
    category: 'essentials',
    color: 'var(--green)',
    icon: 'calculator',
    keywords: ['calculate', 'math', 'add', 'subtract', 'multiply', 'divide', 'sum'],
    presentation: 'sheet',
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    shortDescription: 'Length, weight, temperature & more',
    category: 'essentials',
    color: 'var(--blue)',
    icon: 'converter',
    keywords: [
      'convert',
      'units',
      'cm to inches',
      'kg to lbs',
      'celsius',
      'fahrenheit',
      'length',
      'weight',
      'temperature',
      'volume',
      'speed',
      'area',
      'data',
      'mb to gb',
    ],
    presentation: 'sheet',
  },
  {
    id: 'timer',
    name: 'Timer',
    shortDescription: 'Countdown timer',
    category: 'essentials',
    color: 'var(--purple)',
    icon: 'timer',
    keywords: ['countdown', 'alarm', 'time', 'clock'],
    presentation: 'sheet',
  },
  {
    id: 'stopwatch',
    name: 'Stopwatch',
    shortDescription: 'Stopwatch with laps',
    category: 'essentials',
    color: 'var(--pink)',
    icon: 'timer',
    keywords: ['stopwatch', 'lap', 'time', 'clock', 'race'],
    presentation: 'sheet',
  },
  {
    id: 'alarm',
    name: 'Alarm',
    shortDescription: 'Wakes you even with the app closed',
    category: 'essentials',
    color: 'var(--red)',
    icon: 'bell',
    keywords: ['alarm', 'wake', 'wake up', 'clock', 'ring', 'snooze', 'morning'],
    presentation: 'page',
  },
  {
    id: 'random-generator',
    name: 'Random Generator',
    shortDescription: 'Dice, coin, number, pick from list',
    category: 'more',
    color: 'var(--teal)',
    icon: 'dice',
    keywords: ['dice', 'coin', 'flip', 'random', 'pick', 'choose', 'lottery', 'roll'],
    presentation: 'sheet',
  },
  {
    id: 'notes',
    name: 'Notes',
    shortDescription: 'Create, edit and pin notes',
    category: 'productivity',
    color: 'var(--pink)',
    icon: 'note',
    keywords: ['note', 'write', 'memo', 'text', 'idea'],
    presentation: 'page',
  },
  {
    id: 'checklist',
    name: 'Checklist',
    shortDescription: 'Multiple lists, check off items',
    category: 'productivity',
    color: 'var(--yellow)',
    icon: 'checklist',
    keywords: ['checklist', 'todo', 'to-do', 'list', 'tasks', 'shopping list'],
    presentation: 'page',
  },
  {
    id: 'age-calculator',
    name: 'Age Calculator',
    shortDescription: 'How old am I?',
    category: 'more',
    color: 'var(--orange)',
    icon: 'cake',
    keywords: ['age', 'how old', 'birthday', 'birthdate'],
    presentation: 'sheet',
  },
  {
    id: 'date-calculator',
    name: 'Date Calculator',
    shortDescription: 'Date difference, add or subtract days',
    category: 'more',
    color: 'var(--blue)',
    icon: 'calendar',
    keywords: ['date', 'days between', 'add days', 'subtract days', 'difference'],
    presentation: 'sheet',
  },
  {
    id: 'expense-tracker',
    name: 'Expense Tracker',
    shortDescription: 'Track spending by category',
    category: 'finance',
    color: 'var(--orange)',
    icon: 'wallet',
    keywords: ['expense', 'spending', 'money', 'track', 'purchase', 'cost'],
    presentation: 'page',
  },
  {
    id: 'budget',
    name: 'Budget',
    shortDescription: 'Monthly limits vs spending',
    category: 'finance',
    color: 'var(--teal)',
    icon: 'budget',
    keywords: ['budget', 'limit', 'monthly', 'save', 'savings'],
    presentation: 'page',
  },
  {
    id: 'tip-calculator',
    name: 'Tip Calculator',
    shortDescription: 'Calculate tip and total',
    category: 'finance',
    color: 'var(--red)',
    icon: 'receipt',
    keywords: ['tip', 'gratuity', 'restaurant', 'how much to tip'],
    presentation: 'sheet',
  },
  {
    id: 'split-bill',
    name: 'Split Bill',
    shortDescription: 'Split a bill between people',
    category: 'finance',
    color: 'var(--pink)',
    icon: 'receipt',
    keywords: ['split', 'bill', 'how much do i owe', 'divide bill', 'share bill'],
    presentation: 'sheet',
  },
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    shortDescription: 'X% of Y, percent change & more',
    category: 'essentials',
    color: 'var(--yellow)',
    icon: 'percent',
    keywords: ['percent', 'percentage', 'discount', 'markup', 'percent change', 'percent of'],
    presentation: 'sheet',
  },
  {
    id: 'scientific-calculator',
    name: 'Scientific Calculator',
    shortDescription: 'Trig, logs, powers & constants',
    category: 'essentials',
    color: 'var(--orange)',
    icon: 'function',
    keywords: ['scientific', 'sin', 'cos', 'tan', 'log', 'sqrt', 'power', 'trig', 'exponent'],
    presentation: 'sheet',
  },
  {
    id: 'time-zone',
    name: 'Time Zone',
    shortDescription: 'World clock across cities',
    category: 'more',
    color: 'var(--purple)',
    icon: 'globe',
    keywords: ['time zone', 'timezone', 'world clock', 'city time', 'utc'],
    presentation: 'page',
  },
  {
    id: 'time-difference',
    name: 'Time Difference',
    shortDescription: 'Duration between two moments',
    category: 'more',
    color: 'var(--pink)',
    icon: 'clock',
    keywords: ['time difference', 'duration', 'elapsed', 'how long', 'between two times'],
    presentation: 'sheet',
  },
  {
    id: 'subscription-calculator',
    name: 'Subscription Calculator',
    shortDescription: 'Track recurring subscription costs',
    category: 'finance',
    color: 'var(--blue)',
    icon: 'repeat',
    keywords: ['subscription', 'recurring', 'monthly cost', 'yearly cost', 'streaming'],
    presentation: 'page',
  },
  {
    id: 'debt-calculator',
    name: 'Debt Tracker',
    shortDescription: 'Who owes you, and who you owe',
    category: 'finance',
    color: 'var(--purple)',
    icon: 'card',
    keywords: ['debt', 'iou', 'owe', 'lend', 'borrow', 'money', 'friends'],
    presentation: 'sheet',
  },
  {
    id: 'compass',
    name: 'Compass',
    shortDescription: 'Find true and magnetic north',
    category: 'essentials',
    color: 'var(--teal)',
    icon: 'compass',
    keywords: ['compass', 'direction', 'north', 'heading', 'navigate'],
    presentation: 'page',
  },
  {
    id: 'flashlight',
    name: 'Flashlight',
    shortDescription: 'Turn your camera flash into a light',
    category: 'essentials',
    color: 'var(--yellow)',
    icon: 'flashlight',
    keywords: ['flashlight', 'torch', 'light', 'flash'],
    presentation: 'page',
  },
  {
    id: 'qr-scanner',
    name: 'QR Scanner',
    shortDescription: 'Scan QR codes with your camera',
    category: 'essentials',
    color: 'var(--green)',
    icon: 'scan',
    keywords: ['qr', 'qr code', 'scan', 'scanner', 'camera'],
    presentation: 'page',
  },
  {
    id: 'barcode-scanner',
    name: 'Barcode Scanner',
    shortDescription: 'Scan product & other barcodes',
    category: 'essentials',
    color: 'var(--blue)',
    icon: 'barcode',
    keywords: ['barcode', 'scan', 'scanner', 'product', 'upc', 'ean'],
    presentation: 'page',
  },
];

export function getToolById(id: string): ToolMeta | undefined {
  return TOOLS.find((tool) => tool.id === id);
}

export function getToolsByCategory(category: ToolMeta['category']): ToolMeta[] {
  return TOOLS.filter((tool) => tool.category === category);
}
